// This file is generated by the FlutterFire CLI or can be created manually
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError('Unsupported platform');
    }
  }

static const FirebaseOptions android = FirebaseOptions(
  apiKey: 'AIzaSyClyNs_NOcgF3Qnubk0oiuNGMfU838VEbk',
  appId: '1:301751146015:android:e24c44cdaca956f27ee72a',
  messagingSenderId: '301751146015',  // This is your project_number from the JSON
  projectId: 'ascentra-13105',
  storageBucket: 'ascentra-13105.firebasestorage.app'  // Adding storage bucket as well
);

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8PIuynOnDbvjDvWehx9XLSpaHfK3Z6L4',
    appId: '1:301751146015:ios:a57bc092ebb5e9b57ee72a',
    messagingSenderId: '301751146015',
    projectId: 'ascentra-13105',
    storageBucket: 'ascentra-13105.firebasestorage.app'
  );
}